import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DarkModeProvider } from "../context/DarkModeContext";
import DarkModeToggle from "../components/DarkModeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white dark:bg-dark-background text-gray-900 dark:text-dark-text`}
      >
        <DarkModeProvider>
          <div className="min-h-screen flex flex-col">
            <header className="p-4 flex justify-end">
              <DarkModeToggle />
            </header>
            <main className="flex-grow">{children}</main>
          </div>
        </DarkModeProvider>
      </body>
    </html>
  );
}
